[package]
name = "noctavox"
version = "0.2.3"
edition = "2024"
authors = ["Jaxx497"]
description = "A lightweight TUI music player for local files"
license = "MIT"
repository = "https://github.com/Jaxx497/NoctaVox/"
keywords = ["tui", "music", "audio", "player", "terminal"]
categories = ["multimedia::audio", "command-line-utilities"]

[dependencies]
anyhow = "1.0.102"
crossbeam = { version = "0.8.4", default-features = false, features = ["crossbeam-channel", "crossbeam-queue"] }
dirs = "6.0.0"
fuzzy-matcher = "0.3.7"
indexmap = "2.13.0"
lofty = "0.23.2"
nohash-hasher = "0.2.0"
rand = "0.10.0"
ratatui = {version = "0.30.0", features = ["serde"]}
rayon = "1.11.0"
rusqlite = { version = "0.38.0", features = ["bundled"] }
serde = { version = "1.0.228", features = ["derive"]}
spectrum-analyzer = "1.7.0"
toml = "1.0.3"
ratatui-textarea = "0.8.0"
walkdir = "2.5.0"
unicode-normalization = "0.1.25"
unicode-width = "0.2.2"
voxio = {verison = "0.1.1", path = "../voxio/" }
xxhash-rust = { version = "0.8.15", features = ["xxh3"] }

[[bin]]
name = "vox"
path = "src/main.rs"
